Document: python-cfclient
Title: Debian python-cfclient Manual
Author: <insert document author here>
Abstract: This manual describes what python-cfclient is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-cfclient/python-cfclient.sgml.gz

Format: postscript
Files: /usr/share/doc/python-cfclient/python-cfclient.ps.gz

Format: text
Files: /usr/share/doc/python-cfclient/python-cfclient.text.gz

Format: HTML
Index: /usr/share/doc/python-cfclient/html/index.html
Files: /usr/share/doc/python-cfclient/html/*.html
